services:
  clash:
    image: ghcr.io/Endmoying/clash-docker:main
    # build: .
    container_name: clash
    restart: always
    # command: [ "-d", "/root/.config/clash", "-ext-ui", "/dashboard", "-ext-ctl", "127.0.0.1:9090"] # please set ext-ctl in env not here
    env_file:
      - .env
    volumes:
      - ./config:/root/.config/clash
